# Generated by Django 4.2.9 on 2024-01-15 05:58

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='page_pics/', verbose_name='Image')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
            },
        ),
        migrations.CreateModel(
            name='AboutPageStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=70, verbose_name='Job')),
                ('description', models.TextField(max_length=500)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_about.aboutpage', verbose_name='Page')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page staff',
                'verbose_name_plural': 'Page staff',
            },
        ),
        migrations.CreateModel(
            name='AboutPageCarts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Content')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_about.aboutpage', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Page Cart',
                'verbose_name_plural': 'Page Carts',
            },
        ),
    ]
