# Generated by Django 4.2.9 on 2024-01-17 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact_about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecarts',
            name='icon',
            field=models.ImageField(null=True, upload_to='page_pics/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='aboutpagestaff',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
