# Generated by Django 4.2.9 on 2024-01-17 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact_about', '0002_aboutpagecarts_icon_alter_aboutpagestaff_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
