# Generated by Django 4.2.9 on 2024-01-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_about', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='user',
        ),
    ]
