# Generated by Django 4.2.9 on 2024-01-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_about', '0005_rename_name_contact_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='username',
        ),
    ]
