# Generated by Django 4.2.9 on 2024-01-06 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_postcomment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
